version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "wQTLc17n"
      ACCEPT_EULA: "Y"
  web:
    build:
      context: .
      dockerfile: TravelBug/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      travel_bug_token_key: "travel_bug_secret"
