version: "3"
services:
  web:
    build:
      context: .
      dockerfile: TravelBug/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "wQTLc1%7"
      ACCEPT_EULA: "Y"
